name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest # [macos-latest, windows-latest]
    strategy:
      matrix:
        python-version: ["3.8", "3.13"]
    name: Python ${{ matrix.python-version }} Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install .
      - name: Test single image
        run: python -c "from googledrivedownloader import download_file_from_google_drive; download_file_from_google_drive(file_id='1H1ett7yg-TdtTt6mj2jwmeGZaC8iY1CH', dest_path='data/crossing.jpg')"
      - name: Test zip file
        run: python -c "from googledrivedownloader import download_file_from_google_drive; download_file_from_google_drive(file_id='13nD8T7_Q9fkQzq9bXF2oasuIZWao8uio', dest_path='data/docs.zip', unzip=True)"